version: 2
jobs:
  build:
    working_directory: ~/workdir
    docker:
      - image: quay.io/klira/gradle-with-docker-client
    steps:
      - checkout
      - restore_cache:
          key: circleci-{{ checksum "build.gradle.kts" }}
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: circleci-{{ checksum "build.gradle.kts" }}
      - run: ./gradlew build
      - run: ./gradlew test
      - setup_remote_docker
      - run: |
          docker login -u $HUB_USERNAME -p $HUB_PASSWORD
          ./gradlew jib

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: org-global
