version: 2
jobs:
  build:
    working_directory: ~/workdir
    docker:
      - image: quay.io/klira/gradle-with-docker-client
    steps:
      - checkout
      - restore_cache:
          key: circleci-{{ checksum "build.gradle" }}
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: circleci-{{ checksum "build.gradle" }}
      - run: gradle build
      - run: gradle test
      - run: gradle -d integrationTest
      - setup_remote_docker
      - run: |
          docker login -u $HUB_USERNAME -p $HUB_PASSWORD
          gradle jib
