apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg-{{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "name" . }}
data:
  routes.toml: {{ .Values.routes | quote }}
