apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: leiaauths.leia.klira.io
spec:
  group: leia.klira.io
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: leiaauths
    singular: leiaauth
    kind: LeiaAuthProviders
    shortNames:
      - lap
