title = "Sample config"

[[routes]]
	path = "/"
	topic = "test"
	verify = false
	format = "proto"
	methods = [ "POST", "GET", "HEAD" ]

[[routes]]
	path = "/with_cors"
	topic = "test"
	format = "proto"
	methods = [ "POST", "GET", "HEAD" ]
    cors = [ "http://example.com" ]

[[routes]]
	path = "/json"
	topic = "test"
	verify = false
	format = "proto"
	methods = [ "POST" ]
    validateJson = true
    jsonSchema = """
{
  "$id": "https://example.com/person.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "firstName": {
      "type": "string",
      "description": "The person's first name."
    },
    "lastName": {
      "type": "string",
      "description": "The person's last name."
    },
    "age": {
      "description": "Age in years which must be equal to or greater than zero.",
      "type": "integer",
      "minimum": 0
    }
  }
}
"""

[[sink-providers]]
    name = "kafka"
    type = "kafka"
    default = true
    [sink-providers.options]
        host = "kafka:9092"


#[[sink-providers]]
#    name = "redis"
#    type = "redis"
#    [sink-providers.options]
#        host = "localhost"
#        port = "6379"

#[[sink-providers]]
#    name = "gpubsub"
#    type = "gpubsub"
#    [sink-providers.options]
#        projectId = "<your-project-id>"

