title = "Redis config"

[[routes]]
	path = "/redis"
	sink = "redis"
	topic = "test"
	verify = false
	format = "proto"
	methods = [ "POST", "GET", "HEAD", "OPTIONS" ]

[[routes]]
	path = "/redis/with_cors"
	sink = "redis"
	topic = "test"
	format = "proto"
	methods = [ "POST", "GET", "HEAD" ]
    cors = [ "http://example.com" ]

[[routes]]
	path = "/redis/json"
	sink = "redis"
	topic = "test"
	verify = false
	format = "proto"
	methods = [ "POST" ]
    validateJson = true
    jsonSchema = """
{
  "$id": "https://example.com/person.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "firstName": {
      "type": "string",
      "description": "The person's first name."
    },
    "lastName": {
      "type": "string",
      "description": "The person's last name."
    },
    "age": {
      "description": "Age in years which must be equal to or greater than zero.",
      "type": "integer",
      "minimum": 0
    }
  }
}
"""

[[sink-providers]]
    name = "redis"
    type = "redis"
    [sink-providers.options]
        host = "redis"
        port = "6379"
